project:
  type: website
  output-dir: docs



website:
  title: "Hailey Jang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact
        
        
format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

